/**
 * Daily Challenge Templates Seed Data
 *
 * Daily challenges are special quests that rotate daily and provide higher XP rewards.
 * They unlock at level 10 and offer unique gameplay variety.
 */

import type { RequirementDSL } from './schema'

export interface DailyChallengeTemplate {
  id: string
  name: string
  description: string
  type: 'DAILY'
  category: 'MOVEMENT' | 'STRENGTH' | 'RECOVERY' | 'NUTRITION' | 'DISCIPLINE'
  requirement: RequirementDSL
  baseXP: number
  statType: 'STR' | 'AGI' | 'VIT' | 'DISC'
  statBonus: number
  allowPartial: boolean
  minPartialPercent: number | null
  isCore: boolean
  isActive: boolean
}

export const dailyChallenges: DailyChallengeTemplate[] = [
  // MOVEMENT Challenges (AGI)
  {
    id: 'daily-challenge-step-master',
    name: 'Daily Challenge: Step Master',
    description: 'Achieve 20,000 steps in a single day. Push beyond your limits.',
    type: 'DAILY',
    category: 'MOVEMENT',
    requirement: {
      type: 'numeric',
      metric: 'steps',
      operator: 'gte',
      value: 20000,
    },
    baseXP: 250,
    statType: 'AGI',
    statBonus: 3,
    allowPartial: true,
    minPartialPercent: 70,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-marathon-walker',
    name: 'Daily Challenge: Marathon Walker',
    description: 'Walk the distance of a marathon: 42,195 steps (approximately 26.2 miles).',
    type: 'DAILY',
    category: 'MOVEMENT',
    requirement: {
      type: 'numeric',
      metric: 'steps',
      operator: 'gte',
      value: 42195,
    },
    baseXP: 300,
    statType: 'AGI',
    statBonus: 5,
    allowPartial: true,
    minPartialPercent: 60,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-active-hours',
    name: 'Daily Challenge: Active Hours',
    description: 'Stay active for 180 minutes throughout the day.',
    type: 'DAILY',
    category: 'MOVEMENT',
    requirement: {
      type: 'numeric',
      metric: 'exercise_minutes',
      operator: 'gte',
      value: 180,
    },
    baseXP: 200,
    statType: 'AGI',
    statBonus: 2,
    allowPartial: true,
    minPartialPercent: 75,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-early-mover',
    name: 'Daily Challenge: Early Mover',
    description: 'Complete 5,000 steps before 9 AM. The early bird gets the XP.',
    type: 'DAILY',
    category: 'MOVEMENT',
    requirement: {
      type: 'numeric',
      metric: 'morning_steps',
      operator: 'gte',
      value: 5000,
    },
    baseXP: 180,
    statType: 'DISC',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },

  // STRENGTH Challenges (STR)
  {
    id: 'daily-challenge-workout-warrior',
    name: 'Daily Challenge: Workout Warrior',
    description: 'Complete 90 minutes of intense workout in one day.',
    type: 'DAILY',
    category: 'STRENGTH',
    requirement: {
      type: 'numeric',
      metric: 'workout_minutes',
      operator: 'gte',
      value: 90,
    },
    baseXP: 250,
    statType: 'STR',
    statBonus: 3,
    allowPartial: true,
    minPartialPercent: 70,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-double-session',
    name: 'Daily Challenge: Double Session',
    description: 'Complete 2 separate workouts in one day (minimum 30 minutes each).',
    type: 'DAILY',
    category: 'STRENGTH',
    requirement: {
      type: 'numeric',
      metric: 'workout_count',
      operator: 'gte',
      value: 2,
    },
    baseXP: 200,
    statType: 'STR',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-calorie-crusher',
    name: 'Daily Challenge: Calorie Crusher',
    description: 'Burn 800+ active calories through exercise.',
    type: 'DAILY',
    category: 'STRENGTH',
    requirement: {
      type: 'numeric',
      metric: 'active_calories',
      operator: 'gte',
      value: 800,
    },
    baseXP: 220,
    statType: 'STR',
    statBonus: 3,
    allowPartial: true,
    minPartialPercent: 75,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-morning-strength',
    name: 'Daily Challenge: Morning Strength',
    description: 'Complete a strength training session before 8 AM.',
    type: 'DAILY',
    category: 'STRENGTH',
    requirement: {
      type: 'boolean',
      metric: 'morning_workout',
      expected: true,
    },
    baseXP: 180,
    statType: 'DISC',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },

  // RECOVERY Challenges (VIT)
  {
    id: 'daily-challenge-sleep-champion',
    name: 'Daily Challenge: Sleep Champion',
    description: 'Get 9+ hours of quality sleep.',
    type: 'DAILY',
    category: 'RECOVERY',
    requirement: {
      type: 'numeric',
      metric: 'sleep_hours',
      operator: 'gte',
      value: 9,
    },
    baseXP: 200,
    statType: 'VIT',
    statBonus: 3,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-early-sleeper',
    name: 'Daily Challenge: Early Sleeper',
    description: 'Get to bed before 10 PM and sleep for at least 7 hours.',
    type: 'DAILY',
    category: 'RECOVERY',
    requirement: {
      type: 'boolean',
      metric: 'early_sleep',
      expected: true,
    },
    baseXP: 180,
    statType: 'VIT',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-perfect-recovery',
    name: 'Daily Challenge: Perfect Recovery',
    description: 'Complete all recovery activities: 8h sleep, meditation, and stretching.',
    type: 'DAILY',
    category: 'RECOVERY',
    requirement: {
      type: 'compound',
      operator: 'and',
      requirements: [
        {
          type: 'numeric',
          metric: 'sleep_hours',
          operator: 'gte',
          value: 8,
        },
        {
          type: 'boolean',
          metric: 'meditation',
          expected: true,
        },
        {
          type: 'boolean',
          metric: 'stretching',
          expected: true,
        },
      ],
    },
    baseXP: 280,
    statType: 'VIT',
    statBonus: 4,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-rest-day-master',
    name: 'Daily Challenge: Rest Day Master',
    description: 'Take an active rest day: light movement (5k steps) with no intense workouts.',
    type: 'DAILY',
    category: 'RECOVERY',
    requirement: {
      type: 'compound',
      operator: 'and',
      requirements: [
        {
          type: 'numeric',
          metric: 'steps',
          operator: 'gte',
          value: 5000,
        },
        {
          type: 'numeric',
          metric: 'workout_minutes',
          operator: 'lte',
          value: 20,
        },
      ],
    },
    baseXP: 150,
    statType: 'VIT',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },

  // NUTRITION Challenges
  {
    id: 'daily-challenge-protein-powerhouse',
    name: 'Daily Challenge: Protein Powerhouse',
    description: 'Log all meals and hit protein targets for the day.',
    type: 'DAILY',
    category: 'NUTRITION',
    requirement: {
      type: 'boolean',
      metric: 'protein_logged',
      expected: true,
    },
    baseXP: 200,
    statType: 'VIT',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-hydration-hero',
    name: 'Daily Challenge: Hydration Hero',
    description: 'Drink 4 liters (16 cups) of water throughout the day.',
    type: 'DAILY',
    category: 'NUTRITION',
    requirement: {
      type: 'numeric',
      metric: 'water_cups',
      operator: 'gte',
      value: 16,
    },
    baseXP: 150,
    statType: 'VIT',
    statBonus: 1,
    allowPartial: true,
    minPartialPercent: 80,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-meal-timing',
    name: 'Daily Challenge: Meal Timing',
    description: 'Log all meals within proper windows (breakfast by 9am, dinner by 7pm).',
    type: 'DAILY',
    category: 'NUTRITION',
    requirement: {
      type: 'boolean',
      metric: 'meal_timing_perfect',
      expected: true,
    },
    baseXP: 180,
    statType: 'DISC',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },

  // DISCIPLINE Challenges (DISC)
  {
    id: 'daily-challenge-perfect-day',
    name: 'Daily Challenge: Perfect Day',
    description: 'Complete ALL core quests in one day. Show true discipline.',
    type: 'DAILY',
    category: 'DISCIPLINE',
    requirement: {
      type: 'boolean',
      metric: 'all_core_quests_complete',
      expected: true,
    },
    baseXP: 300,
    statType: 'DISC',
    statBonus: 5,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-early-riser',
    name: 'Daily Challenge: Early Riser',
    description: 'Wake up before 6 AM and complete your morning routine.',
    type: 'DAILY',
    category: 'DISCIPLINE',
    requirement: {
      type: 'boolean',
      metric: 'wake_before_6am',
      expected: true,
    },
    baseXP: 180,
    statType: 'DISC',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-screen-free-evening',
    name: 'Daily Challenge: Screen-Free Evening',
    description: 'No screens after 8 PM. Reclaim your evening.',
    type: 'DAILY',
    category: 'DISCIPLINE',
    requirement: {
      type: 'boolean',
      metric: 'screen_free_evening',
      expected: true,
    },
    baseXP: 200,
    statType: 'DISC',
    statBonus: 3,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-meditation-master',
    name: 'Daily Challenge: Meditation Master',
    description: 'Complete 30 minutes of meditation in one sitting.',
    type: 'DAILY',
    category: 'DISCIPLINE',
    requirement: {
      type: 'numeric',
      metric: 'meditation_minutes',
      operator: 'gte',
      value: 30,
    },
    baseXP: 200,
    statType: 'DISC',
    statBonus: 3,
    allowPartial: true,
    minPartialPercent: 70,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-no-alcohol',
    name: 'Daily Challenge: Alcohol-Free Warrior',
    description: 'Complete the entire day without any alcohol consumption.',
    type: 'DAILY',
    category: 'DISCIPLINE',
    requirement: {
      type: 'boolean',
      metric: 'alcohol_free',
      expected: true,
    },
    baseXP: 180,
    statType: 'DISC',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-cold-exposure',
    name: 'Daily Challenge: Cold Exposure',
    description: 'Take a 3-minute cold shower. Build mental toughness.',
    type: 'DAILY',
    category: 'DISCIPLINE',
    requirement: {
      type: 'boolean',
      metric: 'cold_shower',
      expected: true,
    },
    baseXP: 150,
    statType: 'DISC',
    statBonus: 2,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },

  // COMBO Challenges (Multi-category)
  {
    id: 'daily-challenge-total-domination',
    name: 'Daily Challenge: Total Domination',
    description: 'Complete 15k steps, 60 min workout, 8h sleep, and log all meals.',
    type: 'DAILY',
    category: 'DISCIPLINE',
    requirement: {
      type: 'compound',
      operator: 'and',
      requirements: [
        {
          type: 'numeric',
          metric: 'steps',
          operator: 'gte',
          value: 15000,
        },
        {
          type: 'numeric',
          metric: 'workout_minutes',
          operator: 'gte',
          value: 60,
        },
        {
          type: 'numeric',
          metric: 'sleep_hours',
          operator: 'gte',
          value: 8,
        },
        {
          type: 'boolean',
          metric: 'protein_logged',
          expected: true,
        },
      ],
    },
    baseXP: 300,
    statType: 'DISC',
    statBonus: 5,
    allowPartial: false,
    minPartialPercent: null,
    isCore: false,
    isActive: true,
  },
  {
    id: 'daily-challenge-weekend-warrior',
    name: 'Daily Challenge: Weekend Warrior',
    description: 'Complete an extra-long workout (120 min) and hit 25k steps.',
    type: 'DAILY',
    category: 'STRENGTH',
    requirement: {
      type: 'compound',
      operator: 'and',
      requirements: [
        {
          type: 'numeric',
          metric: 'workout_minutes',
          operator: 'gte',
          value: 120,
        },
        {
          type: 'numeric',
          metric: 'steps',
          operator: 'gte',
          value: 25000,
        },
      ],
    },
    baseXP: 300,
    statType: 'STR',
    statBonus: 5,
    allowPartial: true,
    minPartialPercent: 60,
    isCore: false,
    isActive: true,
  },
]
