/**
 * Exercise Seed Data
 * 50+ common exercises across all categories
 */

import { nanoid } from 'nanoid'
import type { ExerciseCategory, MuscleGroup, Equipment, Difficulty } from './schema/exercises'

interface ExerciseSeed {
  name: string
  slug: string
  description: string
  instructions: string[]
  tips: string[]
  category: ExerciseCategory
  primaryMuscle: MuscleGroup
  secondaryMuscles: MuscleGroup[]
  equipment: Equipment
  difficulty: Difficulty
  caloriesPerMinute: number
  isCompound: boolean
}

export const EXERCISES: ExerciseSeed[] = [
  // CHEST
  {
    name: 'Push-Up',
    slug: 'push-up',
    description: 'Classic bodyweight exercise targeting the chest, shoulders, and triceps.',
    instructions: [
      'Start in a plank position with hands slightly wider than shoulder-width',
      'Lower your body until your chest nearly touches the floor',
      'Keep your core tight and body in a straight line',
      'Push back up to the starting position',
    ],
    tips: ['Keep elbows at 45 degrees', 'Engage your core throughout', 'Look slightly forward, not down'],
    category: 'strength',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps', 'core'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 7,
    isCompound: true,
  },
  {
    name: 'Bench Press',
    slug: 'bench-press',
    description: 'Fundamental compound movement for building chest strength and mass.',
    instructions: [
      'Lie on the bench with feet flat on the floor',
      'Grip the bar slightly wider than shoulder-width',
      'Unrack the bar and lower it to mid-chest',
      'Press the bar back up to full extension',
    ],
    tips: ['Squeeze shoulder blades together', 'Drive through your feet', 'Control the descent'],
    category: 'strength',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    caloriesPerMinute: 5,
    isCompound: true,
  },
  {
    name: 'Dumbbell Fly',
    slug: 'dumbbell-fly',
    description: 'Isolation exercise for chest expansion and muscle definition.',
    instructions: [
      'Lie on a flat bench holding dumbbells above your chest',
      'With a slight bend in elbows, lower arms out to the sides',
      'Stop when you feel a stretch in your chest',
      'Squeeze the dumbbells back together at the top',
    ],
    tips: ['Keep the arc wide and controlled', 'Don\'t go too heavy', 'Focus on the stretch'],
    category: 'strength',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    caloriesPerMinute: 4,
    isCompound: false,
  },
  {
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    description: 'Targets the upper chest for complete chest development.',
    instructions: [
      'Set bench to 30-45 degree incline',
      'Press dumbbells up and together above your chest',
      'Lower with control to shoulder level',
      'Press back up to full extension',
    ],
    tips: ['Keep back flat against bench', 'Don\'t bounce at bottom', 'Full range of motion'],
    category: 'strength',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    caloriesPerMinute: 5,
    isCompound: true,
  },

  // BACK
  {
    name: 'Pull-Up',
    slug: 'pull-up',
    description: 'King of back exercises, builds pulling strength and lat width.',
    instructions: [
      'Hang from bar with overhand grip, hands shoulder-width apart',
      'Pull yourself up until chin clears the bar',
      'Lower with control to full arm extension',
      'Repeat without swinging',
    ],
    tips: ['Initiate with lats, not arms', 'Keep core tight', 'Full range of motion'],
    category: 'strength',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'pull_up_bar',
    difficulty: 'intermediate',
    caloriesPerMinute: 10,
    isCompound: true,
  },
  {
    name: 'Barbell Row',
    slug: 'barbell-row',
    description: 'Compound movement for building back thickness and strength.',
    instructions: [
      'Stand with feet hip-width, bend at hips holding barbell',
      'Keep back flat, looking forward',
      'Pull the bar to your lower chest/upper abs',
      'Lower with control and repeat',
    ],
    tips: ['Don\'t round your back', 'Pull with elbows, not hands', 'Squeeze at top'],
    category: 'strength',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'shoulders'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    caloriesPerMinute: 6,
    isCompound: true,
  },
  {
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    description: 'Machine version of pull-up, great for building lat width.',
    instructions: [
      'Sit at the machine, grip the bar wide',
      'Pull the bar down to upper chest',
      'Squeeze shoulder blades together',
      'Control the bar back up',
    ],
    tips: ['Lean back slightly', 'Pull to chest, not behind neck', 'Avoid momentum'],
    category: 'strength',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'cable',
    difficulty: 'beginner',
    caloriesPerMinute: 5,
    isCompound: true,
  },
  {
    name: 'Single-Arm Dumbbell Row',
    slug: 'single-arm-dumbbell-row',
    description: 'Unilateral back exercise for muscle balance and isolation.',
    instructions: [
      'Place one knee and hand on bench for support',
      'Hold dumbbell in free hand, arm extended',
      'Row the dumbbell to your hip',
      'Lower with control and repeat',
    ],
    tips: ['Keep back flat', 'Don\'t rotate torso', 'Full stretch at bottom'],
    category: 'strength',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    caloriesPerMinute: 5,
    isCompound: true,
  },
  {
    name: 'Deadlift',
    slug: 'deadlift',
    description: 'The ultimate compound movement for total body strength.',
    instructions: [
      'Stand with feet hip-width, bar over mid-foot',
      'Hinge at hips, grip bar outside knees',
      'Drive through heels, extending hips and knees',
      'Stand tall, then lower the bar with control',
    ],
    tips: ['Keep bar close to body', 'Back stays neutral', 'Brace your core'],
    category: 'strength',
    primaryMuscle: 'back',
    secondaryMuscles: ['hamstrings', 'glutes', 'core'],
    equipment: 'barbell',
    difficulty: 'advanced',
    caloriesPerMinute: 8,
    isCompound: true,
  },

  // SHOULDERS
  {
    name: 'Overhead Press',
    slug: 'overhead-press',
    description: 'Primary compound movement for shoulder strength and size.',
    instructions: [
      'Stand with feet shoulder-width, bar at shoulder height',
      'Press the bar overhead until arms are fully extended',
      'Lower the bar back to shoulders with control',
      'Keep core tight throughout',
    ],
    tips: ['Don\'t lean back excessively', 'Press in straight line', 'Brace your core'],
    category: 'strength',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    caloriesPerMinute: 5,
    isCompound: true,
  },
  {
    name: 'Lateral Raise',
    slug: 'lateral-raise',
    description: 'Isolation exercise for shoulder width and definition.',
    instructions: [
      'Stand with dumbbells at your sides',
      'Raise arms out to the sides until parallel to floor',
      'Keep slight bend in elbows throughout',
      'Lower with control',
    ],
    tips: ['Lead with elbows', 'Don\'t swing', 'Light weight, high control'],
    category: 'strength',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCompound: false,
  },
  {
    name: 'Face Pull',
    slug: 'face-pull',
    description: 'Essential for rear delts and shoulder health.',
    instructions: [
      'Set cable at face height with rope attachment',
      'Pull rope toward your face, separating the ends',
      'Externally rotate shoulders at the end',
      'Control back to start',
    ],
    tips: ['Keep elbows high', 'Squeeze rear delts', 'Go light for proper form'],
    category: 'strength',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: 'cable',
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCompound: false,
  },

  // ARMS
  {
    name: 'Bicep Curl',
    slug: 'bicep-curl',
    description: 'Classic bicep isolation exercise.',
    instructions: [
      'Stand with dumbbells at your sides, palms forward',
      'Curl the weights up to shoulder level',
      'Squeeze biceps at the top',
      'Lower with control',
    ],
    tips: ['Keep elbows stationary', 'Don\'t swing', 'Full range of motion'],
    category: 'strength',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCompound: false,
  },
  {
    name: 'Tricep Dip',
    slug: 'tricep-dip',
    description: 'Bodyweight exercise for tricep strength.',
    instructions: [
      'Grip parallel bars or bench behind you',
      'Lower your body by bending elbows to 90 degrees',
      'Press back up to full extension',
      'Keep torso upright for tricep focus',
    ],
    tips: ['Don\'t go too deep', 'Keep shoulders down', 'Control the descent'],
    category: 'strength',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    caloriesPerMinute: 6,
    isCompound: true,
  },
  {
    name: 'Tricep Pushdown',
    slug: 'tricep-pushdown',
    description: 'Cable exercise for tricep isolation.',
    instructions: [
      'Stand at cable machine with straight or rope attachment',
      'Keep elbows pinned to your sides',
      'Push the weight down until arms are straight',
      'Control back up to 90 degrees',
    ],
    tips: ['Don\'t let elbows flare', 'Squeeze at bottom', 'Controlled tempo'],
    category: 'strength',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCompound: false,
  },
  {
    name: 'Hammer Curl',
    slug: 'hammer-curl',
    description: 'Targets brachialis and forearms along with biceps.',
    instructions: [
      'Stand with dumbbells at sides, palms facing each other',
      'Curl the weights up keeping neutral grip',
      'Squeeze at the top',
      'Lower with control',
    ],
    tips: ['Keep palms facing inward', 'Alternate arms or together', 'Don\'t swing'],
    category: 'strength',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCompound: false,
  },

  // LEGS
  {
    name: 'Squat',
    slug: 'squat',
    description: 'The king of lower body exercises.',
    instructions: [
      'Stand with bar on upper back, feet shoulder-width',
      'Brace core and sit back and down',
      'Descend until thighs are parallel to floor',
      'Drive through heels to stand',
    ],
    tips: ['Keep chest up', 'Knees track over toes', 'Full depth if mobility allows'],
    category: 'strength',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings', 'core'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    caloriesPerMinute: 8,
    isCompound: true,
  },
  {
    name: 'Goblet Squat',
    slug: 'goblet-squat',
    description: 'Great for learning squat mechanics and building strength.',
    instructions: [
      'Hold a dumbbell or kettlebell at your chest',
      'Stand with feet slightly wider than shoulders',
      'Squat down keeping the weight at your chest',
      'Drive up to standing',
    ],
    tips: ['Elbows push knees out', 'Keep chest up', 'Go deep'],
    category: 'strength',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'dumbbell',
    difficulty: 'beginner',
    caloriesPerMinute: 7,
    isCompound: true,
  },
  {
    name: 'Romanian Deadlift',
    slug: 'romanian-deadlift',
    description: 'Targets hamstrings and glutes through hip hinge pattern.',
    instructions: [
      'Stand with barbell at hips, slight knee bend',
      'Hinge at hips, pushing butt back',
      'Lower bar along legs until hamstring stretch',
      'Drive hips forward to return to standing',
    ],
    tips: ['Keep bar close to legs', 'Soft knees, not bent', 'Feel the hamstring stretch'],
    category: 'strength',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'back'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    caloriesPerMinute: 6,
    isCompound: true,
  },
  {
    name: 'Lunge',
    slug: 'lunge',
    description: 'Unilateral leg exercise for strength and balance.',
    instructions: [
      'Stand tall, step forward with one leg',
      'Lower until both knees are at 90 degrees',
      'Push through front heel to return',
      'Alternate legs or do all on one side',
    ],
    tips: ['Keep torso upright', 'Front knee over ankle', 'Control the descent'],
    category: 'strength',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 7,
    isCompound: true,
  },
  {
    name: 'Leg Press',
    slug: 'leg-press',
    description: 'Machine exercise for heavy leg training.',
    instructions: [
      'Sit in leg press with back flat against pad',
      'Place feet shoulder-width on platform',
      'Lower platform by bending knees to 90 degrees',
      'Press through feet to extend legs',
    ],
    tips: ['Don\'t lock out knees', 'Keep lower back pressed into pad', 'Full range of motion'],
    category: 'strength',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'machine',
    difficulty: 'beginner',
    caloriesPerMinute: 6,
    isCompound: true,
  },
  {
    name: 'Hip Thrust',
    slug: 'hip-thrust',
    description: 'Best exercise for glute development.',
    instructions: [
      'Sit with upper back against bench, bar over hips',
      'Plant feet flat, hip-width apart',
      'Drive through heels, lifting hips until body is in line',
      'Squeeze glutes at top, lower with control',
    ],
    tips: ['Chin tucked', 'Drive through heels', 'Full hip extension'],
    category: 'strength',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings'],
    equipment: 'barbell',
    difficulty: 'intermediate',
    caloriesPerMinute: 5,
    isCompound: true,
  },
  {
    name: 'Calf Raise',
    slug: 'calf-raise',
    description: 'Isolation exercise for calf development.',
    instructions: [
      'Stand on edge of step or calf machine',
      'Lower heels below the platform',
      'Rise up onto balls of feet',
      'Squeeze calves at top, lower with control',
    ],
    tips: ['Full range of motion', 'Pause at bottom stretch', 'Control the negative'],
    category: 'strength',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 3,
    isCompound: false,
  },
  {
    name: 'Bulgarian Split Squat',
    slug: 'bulgarian-split-squat',
    description: 'Advanced single-leg exercise for leg development.',
    instructions: [
      'Stand with rear foot elevated on bench behind you',
      'Lower until front thigh is parallel to floor',
      'Drive through front heel to return',
      'Keep torso upright throughout',
    ],
    tips: ['Front knee over ankle', 'Don\'t lean forward', 'Start bodyweight only'],
    category: 'strength',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    caloriesPerMinute: 7,
    isCompound: true,
  },

  // CORE
  {
    name: 'Plank',
    slug: 'plank',
    description: 'Fundamental core stability exercise.',
    instructions: [
      'Get in push-up position on forearms',
      'Keep body in straight line from head to heels',
      'Engage core and glutes',
      'Hold for prescribed time',
    ],
    tips: ['Don\'t let hips sag', 'Keep breathing', 'Squeeze glutes'],
    category: 'strength',
    primaryMuscle: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 4,
    isCompound: false,
  },
  {
    name: 'Dead Bug',
    slug: 'dead-bug',
    description: 'Core stability exercise that protects the lower back.',
    instructions: [
      'Lie on back with arms toward ceiling, legs at 90 degrees',
      'Lower opposite arm and leg toward floor',
      'Keep lower back pressed into floor',
      'Return and repeat other side',
    ],
    tips: ['Move slowly and controlled', 'Don\'t arch back', 'Breathe out as you extend'],
    category: 'strength',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 3,
    isCompound: false,
  },
  {
    name: 'Hanging Leg Raise',
    slug: 'hanging-leg-raise',
    description: 'Advanced core exercise targeting lower abs.',
    instructions: [
      'Hang from pull-up bar with arms straight',
      'Keeping legs straight, raise them to 90 degrees',
      'Lower with control without swinging',
      'Repeat for prescribed reps',
    ],
    tips: ['No swinging', 'Control the descent', 'Start with bent knees if needed'],
    category: 'strength',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'pull_up_bar',
    difficulty: 'advanced',
    caloriesPerMinute: 5,
    isCompound: false,
  },
  {
    name: 'Russian Twist',
    slug: 'russian-twist',
    description: 'Rotational core exercise for obliques.',
    instructions: [
      'Sit with knees bent, lean back 45 degrees',
      'Hold weight at chest or clasp hands together',
      'Rotate torso to touch floor beside hip',
      'Rotate to other side',
    ],
    tips: ['Keep chest up', 'Rotate from core, not arms', 'Feet can be elevated for harder'],
    category: 'strength',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 5,
    isCompound: false,
  },
  {
    name: 'Ab Wheel Rollout',
    slug: 'ab-wheel-rollout',
    description: 'Advanced anti-extension core exercise.',
    instructions: [
      'Kneel with hands on ab wheel',
      'Roll wheel forward, extending body',
      'Go as far as you can control',
      'Roll back to start using your abs',
    ],
    tips: ['Keep back flat', 'Don\'t let hips drop', 'Start with partial range'],
    category: 'strength',
    primaryMuscle: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: 'bodyweight',
    difficulty: 'advanced',
    caloriesPerMinute: 6,
    isCompound: false,
  },

  // CARDIO
  {
    name: 'Burpee',
    slug: 'burpee',
    description: 'Full body cardio exercise that builds conditioning.',
    instructions: [
      'Stand, then squat and place hands on floor',
      'Jump feet back to plank position',
      'Do a push-up, then jump feet forward',
      'Jump up with arms overhead',
    ],
    tips: ['Keep a steady pace', 'Modify by stepping instead of jumping', 'Land softly'],
    category: 'cardio',
    primaryMuscle: 'full_body',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    caloriesPerMinute: 12,
    isCompound: true,
  },
  {
    name: 'Mountain Climber',
    slug: 'mountain-climber',
    description: 'Dynamic core and cardio exercise.',
    instructions: [
      'Start in push-up position',
      'Drive one knee toward chest',
      'Quickly switch legs',
      'Continue alternating at a rapid pace',
    ],
    tips: ['Keep hips down', 'Core stays tight', 'Breathe rhythmically'],
    category: 'cardio',
    primaryMuscle: 'core',
    secondaryMuscles: ['shoulders', 'quads'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 10,
    isCompound: true,
  },
  {
    name: 'Jump Squat',
    slug: 'jump-squat',
    description: 'Explosive lower body exercise.',
    instructions: [
      'Stand with feet shoulder-width',
      'Lower into a squat',
      'Explode up into a jump',
      'Land softly and immediately go into next rep',
    ],
    tips: ['Land softly on balls of feet', 'Use arms for momentum', 'Full squat depth'],
    category: 'plyometric',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'calves'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    caloriesPerMinute: 10,
    isCompound: true,
  },
  {
    name: 'Box Jump',
    slug: 'box-jump',
    description: 'Plyometric exercise for lower body power.',
    instructions: [
      'Stand facing a sturdy box',
      'Bend knees and swing arms back',
      'Explode up onto the box, landing softly',
      'Step down and repeat',
    ],
    tips: ['Start with lower box', 'Land softly with bent knees', 'Step down, don\'t jump'],
    category: 'plyometric',
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'calves'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    caloriesPerMinute: 10,
    isCompound: true,
  },
  {
    name: 'Jumping Jack',
    slug: 'jumping-jack',
    description: 'Classic cardio exercise for warm-up and conditioning.',
    instructions: [
      'Stand with feet together, arms at sides',
      'Jump feet out while raising arms overhead',
      'Jump feet back together, lowering arms',
      'Repeat at a steady pace',
    ],
    tips: ['Land softly', 'Keep a rhythm', 'Maintain good posture'],
    category: 'cardio',
    primaryMuscle: 'full_body',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 8,
    isCompound: true,
  },
  {
    name: 'High Knees',
    slug: 'high-knees',
    description: 'Running in place with exaggerated knee lift.',
    instructions: [
      'Stand tall with feet hip-width',
      'Run in place, driving knees up to hip height',
      'Pump arms in sync with legs',
      'Stay on balls of feet',
    ],
    tips: ['Stay upright', 'Quick, light footwork', 'Drive knees up, not forward'],
    category: 'cardio',
    primaryMuscle: 'quads',
    secondaryMuscles: ['core', 'calves'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 9,
    isCompound: true,
  },
  {
    name: 'Kettlebell Swing',
    slug: 'kettlebell-swing',
    description: 'Explosive hip hinge for power and conditioning.',
    instructions: [
      'Stand with kettlebell between feet',
      'Hinge at hips, swing kettlebell back between legs',
      'Explosively drive hips forward, swinging bell to chest height',
      'Control back down into next rep',
    ],
    tips: ['Power comes from hips, not arms', 'Squeeze glutes at top', 'Keep core braced'],
    category: 'strength',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'core', 'shoulders'],
    equipment: 'kettlebell',
    difficulty: 'intermediate',
    caloriesPerMinute: 10,
    isCompound: true,
  },

  // FLEXIBILITY
  {
    name: 'Downward Dog',
    slug: 'downward-dog',
    description: 'Yoga pose for full body stretch and shoulder stability.',
    instructions: [
      'Start on hands and knees',
      'Lift hips up and back, forming inverted V',
      'Press heels toward floor',
      'Hold while breathing deeply',
    ],
    tips: ['Bend knees if hamstrings are tight', 'Spread fingers wide', 'Relax your head'],
    category: 'flexibility',
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['shoulders', 'calves'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 3,
    isCompound: false,
  },
  {
    name: 'Hip Flexor Stretch',
    slug: 'hip-flexor-stretch',
    description: 'Essential stretch for tight hip flexors from sitting.',
    instructions: [
      'Kneel on one knee, other foot in front',
      'Push hips forward gently',
      'Keep torso upright',
      'Hold for 30-60 seconds each side',
    ],
    tips: ['Squeeze glute of back leg', 'Don\'t arch lower back', 'Breathe and relax into it'],
    category: 'flexibility',
    primaryMuscle: 'quads',
    secondaryMuscles: ['core'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 2,
    isCompound: false,
  },
  {
    name: 'Pigeon Pose',
    slug: 'pigeon-pose',
    description: 'Deep hip opener for glutes and hip rotation.',
    instructions: [
      'From all fours, bring one knee forward behind wrist',
      'Extend other leg straight behind you',
      'Lower hips toward floor',
      'Hold and breathe deeply',
    ],
    tips: ['Keep hips square', 'Use props if needed', 'Don\'t force depth'],
    category: 'flexibility',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['quads'],
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    caloriesPerMinute: 2,
    isCompound: false,
  },
  {
    name: 'Cat-Cow',
    slug: 'cat-cow',
    description: 'Spine mobility exercise for warm-up and back health.',
    instructions: [
      'Start on hands and knees',
      'Cow: Drop belly, lift head and tailbone',
      'Cat: Round back, tuck chin and tailbone',
      'Flow between positions with breath',
    ],
    tips: ['Move with breath', 'Full range of motion', 'Keep it slow and controlled'],
    category: 'flexibility',
    primaryMuscle: 'back',
    secondaryMuscles: ['core'],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 2,
    isCompound: false,
  },
  {
    name: 'World\'s Greatest Stretch',
    slug: 'worlds-greatest-stretch',
    description: 'Dynamic stretch that hits multiple areas at once.',
    instructions: [
      'Step into a deep lunge',
      'Place both hands inside front foot',
      'Rotate toward front leg, reaching arm to ceiling',
      'Return hand down, repeat other side',
    ],
    tips: ['Keep back leg straight', 'Sink into the lunge', 'Breathe through each rotation'],
    category: 'flexibility',
    primaryMuscle: 'full_body',
    secondaryMuscles: [],
    equipment: 'bodyweight',
    difficulty: 'beginner',
    caloriesPerMinute: 3,
    isCompound: false,
  },
]

export function getExerciseSeedData() {
  return EXERCISES.map((e) => ({
    id: nanoid(),
    name: e.name,
    slug: e.slug,
    description: e.description,
    instructions: JSON.stringify(e.instructions),
    tips: JSON.stringify(e.tips),
    category: e.category,
    primaryMuscle: e.primaryMuscle,
    secondaryMuscles: JSON.stringify(e.secondaryMuscles),
    equipment: e.equipment,
    difficulty: e.difficulty,
    caloriesPerMinute: e.caloriesPerMinute,
    isCompound: e.isCompound,
    createdAt: new Date(),
  }))
}
